`const_sv2` - README update to comply with docs standards
stratum-mining/stratum pull request #1198
Opened 2024-10-09 10:24 UTC by GitGab19

This PR adds new badges, complying `const_sv2` README.md to [docs standards](https://github.com/stratum-mining/stratum/discussions/970#discussioncomment-10765850)

2024-10-09 10:39 UTC, Shourya742 approved these changes
ACK

2024-10-09 13:47 UTC, rrybarczyk requested changes

2024-10-09 13:47 UTC, rrybarczyk commented on protocols/v2/const-sv2/README.md
> +[![docs.rs](https://codecov.io/gh/stratum-mining/stratum/branch/main/graph/badge.svg)](https://app.codecov.io/gh/stratum-mining/stratum/tree/main/protocols%2Fv2%2Fconst-sv2)
Remove since this crate does not have unit tests and this is the global repo code cov:

```suggestion
```

2024-10-09 13:47 UTC, rrybarczyk commented on protocols/v2/const-sv2/Cargo.toml
> +description = "SV2 constants"
After discussing, we want to continue using "Stratum V2" and "Sv2::

```suggestion
description = "Sv2 constants"
```

2024-10-09 13:47 UTC, rrybarczyk commented on protocols/v2/const-sv2/README.md
> +To include this crate in your project, you can run the following command in your terminal:
```suggestion
To include this crate in your project, run:
```

2024-10-09 15:07 UTC, GitGab19 commented
@rrybarczyk I requested your review, I just tackled your previous comments

2024-10-09 15:46 UTC, rrybarczyk requested changes
The changes you made look good, I just noticed a couple other small things.

2024-10-09 15:46 UTC, rrybarczyk commented on protocols/v2/const-sv2/README.md
>  - **Protocol Constants**: Define key protocol discriminants, message types, and sizes for the SV2 binary protocol.
```suggestion
- **Protocol Constants**: Define key protocol discriminants, message types, and sizes for the Sv2 binary protocol.
```

2024-10-09 15:46 UTC, rrybarczyk commented on protocols/v2/const-sv2/README.md
>  - **Encryption Support**: Includes constants for encryption using ChaChaPoly and ElligatorSwift encoding.
```suggestion
- **Encryption Support**: Includes constants for encryption using `ChaChaPoly` and `ElligatorSwift` encoding.
```

2024-10-09 15:46 UTC, rrybarczyk commented on protocols/v2/const-sv2/README.md
> +```bash
Can both `bash` and `sh` be used interchangeably here? Does using `sh` change the syntax coloring? If there is not difference, leave as `bash`.

```suggestion
```sh
```

2024-10-09 16:32 UTC, GitGab19 commented
> The changes you made look good, I just noticed a couple other small things.

Done c9b7ca81ee81f75e4149387459120a3e8680f34f

2024-10-09 17:56 UTC, rrybarczyk approved these changes

2024-10-10 10:41 UTC, jbesraa reviewed
Added one small nit

2024-10-10 10:41 UTC, jbesraa commented on protocols/v2/const-sv2/Cargo.toml
> +description = "Sv2 constants"
```suggestion
description = "This crate holds all of the shared constants used across the different Stratum V2 protocols and roles crates"
```

2024-10-10 10:57 UTC, GitGab19 commented on protocols/v2/const-sv2/Cargo.toml
> +description = "Sv2 constants"
Done here 09b2833261a0096fd742a740f4f44b2c9ad1abf2

2024-10-10 10:58 UTC, jbesraa approved these changes

2024-10-10 11:53 UTC, merged