chore: combine ci
stratum-mining/stratum pull request #1312
Opened 2024-12-20 04:09 UTC by devworlds

Hello, as required try to combine all asked yamls in only one yaml to ci/cd separated by jobs.

2024-12-20 12:21 UTC, jbesraa requested changes
Thanks for looking into this. i'am yet to give it a thorough review but can you please fix ci https://github.com/stratum-mining/stratum/actions/runs/12425379179/workflow ?

2024-12-20 13:25 UTC, devworlds commented
> Thanks for looking into this. i'am yet to give it a thorough review but can you please fix ci https://github.com/stratum-mining/stratum/actions/runs/12425379179/workflow ?

sure, i do it as a syntax test and forgot to fix

2024-12-20 13:29 UTC, devworlds commented
you think that we can set some pattern to the jobs names? i made just a "draft" to bring to table

2024-12-23 15:38 UTC, jbesraa requested changes
Is there anyway to make this shorter?
Can we try to avoid repeating this following part?
```
   runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
        include:
          - os: macos-latest
            target: x86_64-apple-darwin
          - os: ubuntu-latest
            target: x86_64-unknown-linux-musl

    steps:
      - uses: actions/checkout@v4
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: 1.75.0
          override: true
          components: clippy
```

2024-12-23 21:10 UTC, devworlds commented
something like this?

> Is there anyway to make this shorter? Can we try to avoid repeating this following part?
> 
> ```
>    runs-on: ${{ matrix.os }}
>     strategy:
>       matrix:
>         os:
>           - macos-latest
>           - ubuntu-latest
>         include:
>           - os: macos-latest
>             target: x86_64-apple-darwin
>           - os: ubuntu-latest
>             target: x86_64-unknown-linux-musl
> 
>     steps:
>       - uses: actions/checkout@v4
>       - uses: actions-rs/toolchain@v1
>         with:
>           profile: minimal
>           toolchain: 1.75.0
>           override: true
>           components: clippy
> ```

something like this?

2024-12-24 08:29 UTC, jbesraa requested changes
This is going in the right direction but currently it does not seem to be fully working https://github.com/stratum-mining/stratum/actions/runs/12472789699/workflow

2024-12-24 08:34 UTC, jbesraa commented
You can take some inspiration from here https://github.com/lightningdevkit/rust-lightning/tree/main/ci If you feel the need to move things to a shell script and just invoke it in the GH action. I think that would be also great for local dev env where devs can just call the shell script to replicate the GH action flow.

2024-12-31 17:32 UTC, devworlds commented
You think that is good?

2025-01-06 07:58 UTC, jbesraa requested changes
Looks great! Added a few sugg's for the naming in order to make them consistent. 
I would also create a sub-folder inside `scripts` folder and call it `workflows`, and also align the files names: `build.sh`, `clippy.sh`, `format.sh` and `semver.sh`

2025-01-06 07:58 UTC, jbesraa commented on .github/workflows/general-check.yaml
> +  Msrv-Check:
```suggestion
  MSRV:
```

2025-01-06 07:58 UTC, jbesraa commented on .github/workflows/general-check.yaml
> +  Semver-check:
```suggestion
  SemVer:
```

2025-01-06 07:58 UTC, jbesraa commented on .github/workflows/general-check.yaml
> +  Rust-fmt:
```suggestion
  Format:
```

2025-01-06 07:58 UTC, jbesraa commented on .github/workflows/general-check.yaml
> +  clippy-check-lint:
```suggestion
  Clippy:
```

2025-01-06 13:05 UTC, devworlds commented
> Looks great! Added a few sugg's for the naming in order to make them consistent. I would also create a sub-folder inside `scripts` folder and call it `workflows`, and also align the files names: `build.sh`, `clippy.sh`, `format.sh` and `semver.sh`

Greats sugg's, i hope this help to make the code more clean, and easy to understand to others, and ourselfs too

2025-01-06 13:40 UTC, jbesraa commented on .github/workflows/general-check.yaml
> +  Format:
What do you mean our ci required that?

2025-01-06 13:43 UTC, jbesraa commented on .github/workflows/general-check.yaml
> +  Format:
Is this a definition in the repo settings? maybe we should change that. the naming should be consistent, doing "clippy-check" we should then do "format-check". I dont mind adding the "check" everywhere but I dont think it is necessary.

2025-01-06 13:44 UTC, jbesraa commented
I think we should change `general-check.yml` to `rust-checks`

2025-01-06 14:01 UTC, plebhash commented
I haven't really looked into the contents of the PR, but overall I feel the commit history is getting really dirty

we are introducing changes and later adding new commits to fix things from previous commits

if we merged this PR as it is, our commit history on `main` would be a mess

I highly recommend to the reader to study how to do rebase and squash on `git`

2025-01-06 14:04 UTC, devworlds commented
> I haven't really looked into the contents of the PR, but overall I feel the commit history is getting really dirty
> 
> we are introducing changes and later adding new commits to fix things from previous commits
> 
> if we merged this PR as it is, our commit history on `main` would be a mess
> 
> I highly recommend to the PR author to study how to do rebase and squash on `git`

thanks for advise, i'll look into this!

2025-01-06 16:27 UTC, devworlds commented
before foward with PR, can you guys leave a tip to improve the commits like the plebhash said, it just rebase and squash all my commits to only one? @Shourya742 @jbesraa

2025-01-06 16:38 UTC, jbesraa requested changes
Note that by default we want each job to run on both stable and our-msrv versions unless we specify something different, like for `cargo fmt` we only use `nightly`. Moreover, some of the jobs have OS switch but not others, we should be consistent with this.

Yea I would squash it all into a single commit and add as much context as possible in the commit body while leaving the commit title under ~80 chars.

2025-01-06 16:39 UTC, jbesraa commented on scripts/workflows/test.sh
> +cargo build --manifest-path=benches/Cargo.toml
We should probably move the examples into a separate shell file and put it in a separate job in the workflow

2025-01-06 16:40 UTC, jbesraa commented on .github/workflows/general-check.yaml
> +  Format:
@GitGab19 @plebhash wdyt about changing the settings for this?

2025-01-06 16:46 UTC, devworlds commented on scripts/workflows/test.sh
> +cargo build --manifest-path=benches/Cargo.toml
got it

2025-01-06 16:47 UTC, devworlds commented on scripts/workflows/test.sh
> +cargo build --manifest-path=benches/Cargo.toml
basic this cargo build already was used in build.sh

2025-01-06 16:52 UTC, devworlds commented on scripts/workflows/format.sh
> +#!/bin/bash
got it

2025-01-06 16:52 UTC, devworlds commented
> Note that by default we want each job to run on both stable and our-msrv versions unless we specify something different, like for `cargo fmt` we only use `nightly`. Moreover, some of the jobs have OS switch but not others, we should be consistent with this.
> 
> Yea I would squash it all into a single commit and add as much context as possible in the commit body while leaving the commit title under ~80 chars.

nice, before forward with pr, i will try to make it, i only have fear to break something and can't recover

2025-01-06 17:06 UTC, jbesraa commented on scripts/workflows/test.sh
> +cd ../../..
All of this should be taking out, including L32 and L34. The examples should be moved to `examples.sh` and run in a separate job.
And it would be better to use a loop here similar to the other shell files.

2025-01-06 17:06 UTC, jbesraa commented on scripts/workflows/build.sh
> +cargo build --manifest-path=benches/Cargo.toml
lets use a loop here

2025-01-06 17:09 UTC, jbesraa commented
> > Note that by default we want each job to run on both stable and our-msrv versions unless we specify something different, like for `cargo fmt` we only use `nightly`. Moreover, some of the jobs have OS switch but not others, we should be consistent with this.
> > Yea I would squash it all into a single commit and add as much context as possible in the commit body while leaving the commit title under ~80 chars.
> 
> nice, before forward with pr, i will try to make it, i only have fear to break something and can't recover

We are here to help, just post any problem you get stuck on

2025-01-06 17:19 UTC, devworlds commented on scripts/workflows/test.sh
> +cd ../../..
so.. let me see if i understand, this new file examples.sh will have only the L32, L34 on it, or all theses L2 until L23

2025-01-06 17:21 UTC, devworlds commented on scripts/workflows/test.sh
> +cd ../../..
![image](https://github.com/user-attachments/assets/7e6a160a-bce9-47ca-b339-cfd4d9a0b2e6)
![image](https://github.com/user-attachments/assets/3e4cb250-9d46-4eeb-b5be-41b9ae3fc3b9)
![image](https://github.com/user-attachments/assets/3d9b6aba-fc80-4933-b84a-cfdbd337e552)

something like this?

2025-01-06 17:22 UTC, devworlds commented on scripts/workflows/test.sh
> +cd ../../..
@jbesraa

2025-01-06 17:24 UTC, devworlds commented on scripts/workflows/test.sh
> +cd ../../..
loop on build, loop on test and remove all things and keep just the test, and new script examples, that idk if i understand right

2025-01-06 17:25 UTC, jbesraa commented on scripts/workflows/test.sh
> +cd ../../..
`example.sh` should only include `cargo run --manifest-path=examples/...` while all the `cargo test ..` should live in `test.sh`

2025-01-06 17:27 UTC, devworlds commented on scripts/workflows/test.sh
> +cd ../../..
got it, and we will need a new job on yaml to run this example.sh?

2025-01-06 17:39 UTC, jbesraa commented on scripts/workflows/test.sh
> +cd ../../..
yup.
`examples` maybe?

2025-01-07 11:55 UTC, devworlds commented
i made a rebase but i think that is not what i was expecting, this week i'll focus on understand better how to work with, sorry about that, to be better in nexts issues. but thanks for all help and patience.

2025-01-07 18:46 UTC, devworlds commented
i can't see your comment mate @GitGab19, only that you reviewed something

2025-01-09 08:32 UTC, jbesraa commented
@devworlds lets focus on resolving this pull request https://github.com/stratum-mining/stratum/pull/1316 first, and then you can get back to this one. We prefer to take this one a bit slower as it affects the CI which is going through multiple changes atm.

2025-01-09 10:34 UTC, devworlds commented
For sure

2025-01-09 10:35 UTC, devworlds commented
> @devworlds lets focus on resolving this pull request https://github.com/stratum-mining/stratum/pull/1316 first, and then you can get back to this one. We prefer to take this one a bit slower as it affects the CI which is going through multiple changes atm.


For sure, no worries

2025-03-30 12:47 UTC, GitGab19 commented
Closing this as stale

2025-03-30 12:47 UTC, closed without merging