`subprotocol` crates `no_std` support
stratum-mining/stratum pull request #1315
Opened 2024-12-20 16:24 UTC by Georges760

`common_messages_sv2` `job_declaration_sv2` `mining_sv2` `template_distribution_sv2`: remove the `no_std` feature and make them `#![no_std]` as they never use `std` anywhere.

- bump their MAJOR version because of feature removal
- bump the dependant crates PATCH version
- updates docs

2024-12-23 06:31 UTC, plebhash commented
hey @Georges760 thanks for this

let's try to merge this PR before releasing v1.2.0

bumping MAJOR makes total sense

however some of the PATCH bumps are redundant since they've already been covered via #1300 in preparation for the release v1.2.0, so it would be redundant to bump 2x before publishing the crates to `crates.io`

I'm rebasing the PR to avoid bumping PATCH 2x on crates that have already been bumped via #1300, namely:
- `roles_logic_sv2`
- `sv2_ffi`

I'm also squashing a60cbccec44d8ee60a3eb98f28b1427f138b59c4 for a cleaner commit history

2024-12-23 06:33 UTC, plebhash requested changes
hey @Georges760 thanks for this

let's try to merge this PR before releasing v1.2.0

bumping MAJOR makes total sense

however some of the PATCH bumps are redundant since they've already been covered via #1300 in preparation for the release v1.2.0, so it would be redundant to bump 2x before publishing the crates to `crates.io`

we should rebase the PR to avoid bumping PATCH 2x on crates that have already been bumped via #1300, namely:
- `roles_logic_sv2`
- `sv2_ffi`

we should also squash a60cbccec44d8ee60a3eb98f28b1427f138b59c4 for a cleaner commit history

2024-12-26 08:52 UTC, Georges760 commented
> hey @Georges760 thanks for this
> 
> let's try to merge this PR before releasing v1.2.0
> 
> bumping MAJOR makes total sense
> 
> however some of the PATCH bumps are redundant since they've already been covered via #1300 in preparation for the release v1.2.0, so it would be redundant to bump 2x before publishing the crates to `crates.io`
> 
> we should rebase the PR to avoid bumping PATCH 2x on crates that have already been bumped via #1300, namely:
> 
> * `roles_logic_sv2`
> * `sv2_ffi`
> 
> we should also squash [a60cbcc](https://github.com/stratum-mining/stratum/commit/a60cbccec44d8ee60a3eb98f28b1427f138b59c4) for a cleaner commit history

@plebhash done

2024-12-26 11:39 UTC, plebhash approved these changes

2024-12-26 11:39 UTC, merged