feat: update ProxyConfig in roles to JDCConfig, and update the references
stratum-mining/stratum pull request #1316
Opened 2024-12-21 02:27 UTC by devworlds

Hi, i not found another object with Config, so i changed only ProxyConfig, to check if is what was  wanted.

2024-12-23 15:33 UTC, jbesraa requested changes
Thanks for working on this!

Please go to all of the `main.rs` files inside `roles/[role_name]` and there you can that each different role have its own config. We should change the name in each role to reflect the name of the role. For example, in translator role we should change to `TranslatorConfig`, in jd-server role we should change to `JDSConfig` and so on.

2024-12-23 19:05 UTC, devworlds commented
> Thanks for working on this!
> 
> Please go to all of the `main.rs` files inside `roles/[role_name]` and there you can that each different role have its own config. We should change the name in each role to reflect the name of the role. For example, in translator role we should change to `TranslatorConfig`, in jd-server role we should change to `JDSConfig` and so on.

got it!

2025-01-09 08:29 UTC, jbesraa requested changes
Let me just explain a bit about the project structure. You have the `roles` folder which is a cargo workspace, i.e. it contains multiple crates. Each one of the crates have it is own configuration object. For example, the `translator` role under `roles/translator` have the `roles/translator/src/lib/proxy_config.rs` config. This config should be changed to `TranslatorConfig`.
Whats correct for the `translator` is correct for all the other roles. We have `jd-client` and its config should be `JDCConfig`. We also have `jd-server` and its config should be `JDSConfig` and so on.

Let me know if that is not clear.

2025-03-30 12:48 UTC, GitGab19 commented
Closing this as stale

2025-03-30 12:48 UTC, closed without merging