fix sigterm issue with translator sv2
stratum-mining/stratum pull request #1319
Opened 2024-12-23 12:20 UTC by Shourya742

Partially closes: #1266

The issue lies with the blocking nature of `self.internal_start().await` inside the loop. Since the .await suspends the current task, it prevents the tokio::select! from responding promptly to other events, such as the ctrl_c() signal. This PR tends to spawn to internal_start as a separate task, while still keeping the select! macro active to listen for other events.

2024-12-30 11:02 UTC, jbesraa requested changes
Please make this PR easier to review by undoing the formatting/indentation changes. If you are moving a function outside the `TranslatorSV2` struct, do it in a separate commit and then commit the changes to make the fix

2025-01-03 14:48 UTC, plebhash commented on roles/translator/src/lib/mod.rs
> +        proxy_config: ProxyConfig,
are we changing the signature for this function for any specific purpose?

2025-01-03 15:05 UTC, plebhash commented on roles/translator/src/lib/mod.rs
> +                                error!("SHUTDOWN from: {}", err);
let's bring this change here: https://github.com/stratum-mining/stratum/pull/1295

however I think it's better to make it into a `warn!` instead of `error!`

2025-01-03 15:06 UTC, plebhash commented on roles/translator/src/lib/mod.rs
> +    sync::{broadcast, Notify as notification},
we're not using this alias on #1321 

is that intentional?

if not, we should try to keep the patterns consistent

2025-01-06 13:33 UTC, plebhash approved these changes

2025-01-06 13:37 UTC, plebhash commented
tACK

2025-01-09 08:19 UTC, jbesraa requested changes
Looks good. Just one small nit.

IMO before we merge this or #1321, a test to cover the feature/bug fix should be implemented.

2025-01-09 08:19 UTC, jbesraa commented on roles/translator/src/lib/mod.rs
> +                                    // kill al the tasks
Indentation is a bit off here and in L115

2025-01-09 16:11 UTC, jbesraa commented
This PR is resolving(partially, the translator part) https://github.com/stratum-mining/stratum/issues/1266. 
And #1266 was opened because we were not able to do #1207. IMO in order to make sure this is the solution we want(it might be a solution to a different problem), #1207 need to be resolved.

2025-01-09 16:40 UTC, jbesraa commented
@Shourya742 https://github.com/stratum-mining/stratum/pull/1343 this branch have your code and the test I wrote back then(I did some changes to align it with current API design). Feel free to pick it up, otherwise Ill look into it tomorrow.

2025-01-13 14:39 UTC, jbesraa approved these changes

2025-01-14 17:45 UTC, plebhash approved these changes

2025-01-15 19:23 UTC, merged