fix jdc sigterm signalling issue
stratum-mining/stratum pull request #1321
Opened 2024-12-23 16:40 UTC by Shourya742

closes: https://github.com/stratum-mining/stratum/issues/1266

### Description  
This PR introduces several key changes to the `JobDeclaratorClient` implementation to enhance its functionality, improve shutdown handling, and resolve blocking issues during task execution:  

1. **Use of `tokio::spawn` for Task Initialization**  
   - The `initialize_jd` and `initialize_jd_as_solo_miner` methods are now executed using `tokio::spawn`.  
   - Previously, these methods were directly awaited in the event loop, causing blocking issues on disconnection events. By spawning these tasks, we ensure the event loop remains responsive.  

2. **Refactored Method Signatures**  
   - Adjusted the signatures of `initialize_jd` and `initialize_jd_as_solo_miner` to accept `ProxyConfig` as a parameter instead of relying on `&self`.  
   - This change prevents `self` from being moved into the spawned tasks and allows for proper cloning and reuse within the async context.  

3. **Graceful Shutdown Mechanism**  
   - Introduced a `tokio::sync::Notify` instance as part of `JobDeclaratorClient` struct to handle shutdown signals. Which now gives power to struct initializer to shutdown process directly.
   - Replaced the previous `ctrl_c` signal handling with a task that listens for the signal and triggers the shutdown notifier.  

4. **Simplified Interrupt Signal Handling**  
   - Removed the manual handling of `ctrl_c` interrupt futures within the select loop.  
   - Graceful shutdown now exits the process when the notifier is triggered.

2024-12-30 11:07 UTC, jbesraa requested changes
Please explain in the commit what is the ACTUAL fix. What are you doing in order to fix the issue.

2025-01-03 15:11 UTC, plebhash commented on roles/jd-client/src/lib/mod.rs
> +        proxy_config: ProxyConfig,
are we changing the signature for this function for any specific purpose?

2025-01-03 15:15 UTC, plebhash commented on roles/jd-client/src/lib/mod.rs
>                      task_status = rx_status.recv().fuse() => task_status,
on #1319 we're introducing a `if let Ok` to avoid the `unwrap`

IMO we should also do that here

2025-01-06 13:32 UTC, plebhash commented on roles/jd-client/src/lib/mod.rs
> +                                    error!("Changin Pool");
```suggestion
                                    error!("Chaning Pool");
```

2025-01-06 13:36 UTC, plebhash commented
tACK

I found a typo, but overall LGTM

2025-01-06 13:39 UTC, plebhash approved these changes

2025-01-09 08:10 UTC, jbesraa requested changes
Looking good overall. Added a few nits.

Regarding this commit 6a95deb54ca4c058e72d645c0204bb6528c8fca6 could you please explain why it is added? the title says "move task_status block inside the select macro" but it is not clear why the `task_status` was moved. maybe add that in the commit body.

a0ffe75f8b98764351e35e14a3d0ca1765a8f0a1 could have a better title, maybe "Fix typo", or you could just fix it up to the second commit(a3efa4667cd9231933320b1a5e254dba3167ee19).

2025-01-09 08:10 UTC, jbesraa commented on roles/jd-client/src/lib/mod.rs
> +                    info!("Closing channels");
```rust
info!("Received unknown task. Shutting down.");
```

2025-01-09 08:10 UTC, jbesraa commented on roles/jd-client/src/lib/mod.rs
> +                            break;
would this `break` and the other ones not specifying the loop tag, break the inner or outer one?

2025-01-13 13:31 UTC, jbesraa requested changes
We tested this locally and it seems that the ghost processes are gone! so this is good to go

2025-01-13 13:31 UTC, jbesraa commented on roles/jd-client/src/lib/mod.rs
> +    pub shutdown: Arc<Notify>,
Can you please add a new function to `JobDeclaratorClient::shutdown` to the first commit?

2025-01-13 14:39 UTC, jbesraa approved these changes

2025-01-14 17:44 UTC, plebhash approved these changes

2025-01-15 15:25 UTC, merged

2025-01-16 08:00 UTC, jbesraa commented on roles/jd-client/src/lib/mod.rs
> +    pub fn shutdown(&self) -> Arc<Notify> {
What other scenarios could arise? if they exist then a new function should be added.

2025-01-16 08:01 UTC, jbesraa commented on roles/jd-client/src/lib/mod.rs
> +                        std::process::exit(0);
yea. `break` should be enough IMO as we are already in the outer loop

2025-01-16 08:03 UTC, jbesraa commented on roles/jd-client/src/lib/mod.rs
> +    pub fn shutdown(&self) -> Arc<Notify> {
https://github.com/stratum-mining/stratum/issues/1348

2025-01-16 08:05 UTC, jbesraa commented on roles/jd-client/src/lib/mod.rs
> +                        std::process::exit(0);
https://github.com/stratum-mining/stratum/issues/1349

2025-01-16 08:15 UTC, jbesraa commented on roles/jd-client/src/lib/mod.rs
> +    pub fn shutdown(&self) -> Arc<Notify> {
the `shutdown` signal is only `notified` here https://github.com/stratum-mining/stratum/pull/1321/files/6d1632b2eaca205f4b0e964a7a8d1d4c0b2c5d3a#diff-b344c0ca590735a830cbfb638690b53af5889deeef68717d4586b5da8af62479R171, which is very correct. but it also mean that anyone who is using the shutdown object, can only perform shutdown action. which is also correct, we don't the same signal to perform different actions.

2025-01-16 08:29 UTC, jbesraa commented on roles/jd-client/src/lib/mod.rs
> +    pub fn shutdown(&self) -> Arc<Notify> {
https://github.com/stratum-mining/stratum/issues/1348#issuecomment-2594816492

2025-01-16 08:41 UTC, jbesraa commented on roles/jd-client/src/lib/mod.rs
> +                        std::process::exit(0);
> #1349

https://github.com/stratum-mining/stratum/issues/1351#issuecomment-2594870769