rename config examples
stratum-mining/stratum pull request #726
Opened 2024-01-22 13:50 UTC by plebhash

this topic was already discussed with @Fi3 on a parallel PR that hasn't yet been merged:
https://github.com/stratum-mining/stratum/pull/684#discussion_r1405667147

The naming conventions on `config-examples` of `roles/jd-client` and `roles/translator` were a bit confusing/misleading.

I'm working to update the tutorials from `Getting Started` section of stratumprotocol.org and ideally we should fix this in order to avoid confusion on the community.

I'm sending this PR since #684 is low prio and may not be merged soon, while updating the tutorials is more urgent.

2024-01-22 13:58 UTC, GitGab19 approved these changes

2024-01-22 13:58 UTC, GitGab19 commented on roles/translator/tproxy-config.toml
I would delete this one

2024-01-22 15:25 UTC, GitGab19 commented
@plebhash I would edit the values `min_individual_miner_hashrate` and `channel_nominal_hashrate` (in both config-example files) with the value 10_000_000_000_000 (which are 10Th/s).
Since the real testing is done with ASIC machines, it makes no sense anymore to use the current tiny values in examples config imo.
In any case, I would remind to have a look at that parameter in the instructions as well.

2024-01-22 15:26 UTC, GitGab19 requested changes
@plebhash I would edit the values min_individual_miner_hashrate and channel_nominal_hashrate (in both config-example files) with the value 10_000_000_000_000 (which are 10Th/s).
Since the real testing is done with ASIC machines, it makes no sense anymore to use the current tiny values in examples config imo.
In any case, I would remind to have a look at that parameter in the instructions as well.

2024-01-22 19:07 UTC, plebhash commented on roles/translator/tproxy-config.toml
every role has a `*-config.toml` on the crate root

is there any special reason to delete only for the translator?

2024-01-22 23:33 UTC, GitGab19 commented on roles/translator/tproxy-config.toml
I hadn't paid attention to it :)
I don't like having some configs also in the root, we already provide the examples.
But I'm not 100% against them, I don't know.
What do you think about it?

2024-01-23 00:42 UTC, plebhash commented on roles/translator/tproxy-config.toml
no strong opinions from my side either, but if I had to take a stance, I would agree they are kind of unnecessary

but if we remove from translator, we should remove from every role to keep the same standards

2024-01-23 10:49 UTC, GitGab19 commented on roles/translator/tproxy-config.toml
> no strong opinions from my side either, but if I had to take a stance, I would agree they are kind of unnecessary
> 
> but if we remove from translator, we should remove from every role to keep the same standards

Yeah I totally agree with you.
What do you think about this @Fi3 ?

2024-01-23 12:34 UTC, Fi3 commented on roles/translator/tproxy-config.toml
Is ok to not have them in the crate root. I usally keep them there for convenience and change them very often, so is hard to remeber every time to not commit changed to the config files. Also I noticed that we tend to remove them and then recommit them, if we remove them we should try to remeber it when we do reviews (i'm the first one to forget it). Or maybe just add anc action that fail if the config are there

2024-01-23 12:36 UTC, GitGab19 commented on roles/translator/tproxy-config.toml
> Is ok to not have them in the crate root. I usally keep them there for convenience and change them very often, so is hard to remeber every time to not commit changed to the config files. Also I noticed that we tend to remove them and then recommit them, if we remove them we should try to remeber it when we do reviews (i'm the first one to forget it). Or maybe just add anc action that fail if the config are there

We could add them in the gitignore (?)

2024-01-23 12:44 UTC, Fi3 commented on roles/translator/tproxy-config.toml
yep simpler and better

2024-01-23 14:07 UTC, plebhash commented on roles/translator/tproxy-config.toml
ok I removed the files from all roles and added `/roles/*/*-config.toml` to the root `.gitignore`

2024-01-23 14:24 UTC, plebhash commented
> @plebhash I would edit the values min_individual_miner_hashrate and channel_nominal_hashrate (in both config-example files) with the value 10_000_000_000_000 (which are 10Th/s). Since the real testing is done with ASIC machines, it makes no sense anymore to use the current tiny values in examples config imo. In any case, I would remind to have a look at that parameter in the instructions as well.

ack https://github.com/stratum-mining/stratum/pull/726/commits/db91a8799d1e6d8946f6cc3bfaef56501c15387b

2024-01-23 14:28 UTC, GitGab19 approved these changes

2024-01-23 14:30 UTC, GitGab19 commented
@plebhash can you just add something like `"e.g. 10 Th/s = 10_000_000_000_000"` in the comment before the `min_individual_miner_hashrate `and `channel_nominal_hashrate` of every possible config?
It could help testers in better setting them imo

2024-01-23 14:57 UTC, plebhash commented
> @plebhash can you just add something like `"e.g. 10 Th/s = 10_000_000_000_000"` in the comment before the `min_individual_miner_hashrate `and `channel_nominal_hashrate` of every possible config? It could help testers in better setting them imo

ack https://github.com/stratum-mining/stratum/pull/726/commits/8af1f5f45fd1dd6a8b034103a47814ca910b1c1a

2024-01-23 18:07 UTC, merged