Added non-existent file configuration option
stratum-mining/stratum pull request #859
Opened 2024-04-17 23:20 UTC by rockcoolsaint

Fixed the issue raised in issue #695

### How to test
Do the following:
- cd to `roles/jd-client`
- run `cargo run -- -c ~/no-such-file.toml`

2024-04-17 23:41 UTC, plebhash commented
great job! I was able to test successfully on `roles/jd-client`:
```
$ cargo run -- -c no-such-file.toml
...
2024-04-17T23:34:45.764534Z ERROR jd_client: Error: File 'no-such-file.toml' does not exist!
```

a few remarks:
- although it was not explicitly stated on the original issue description, it would be nice if you could replicate this solution to the `translator` role implementation, because it suffers from the same bug.
- the `Rustfmt` CI test is failing. Please run `cargo fmt` to make sure the code is properly formatted. It is a good practice to do this before every commit, but you could also just add one final commit doing the formatting for all the edited files.

2024-04-17 23:48 UTC, plebhash requested changes
great job! I was able to test successfully on `roles/jd-client`:
```
$ cargo run -- -c no-such-file.toml
...
2024-04-17T23:34:45.764534Z ERROR jd_client: Error: File 'no-such-file.toml' does not exist!
```

a few remarks:
- although it was not explicitly stated on the original issue description, it would be nice if you could replicate this solution to the `translator` role implementation, because it suffers from the same bug.
- the `Rustfmt` CI test is failing. Please run `cargo fmt` to make sure the code is properly formatted. It is a good practice to do this before every commit, but you could also just add one final commit doing the formatting for all the edited files.

2024-04-18 06:14 UTC, Sjors commented
Maybe rename this PR to: "Add error for non-existent configuration file"

2024-04-18 11:41 UTC, rockcoolsaint commented
> great job! I was able to test successfully on `roles/jd-client`:
> 
> ```
> $ cargo run -- -c no-such-file.toml
> ...
> 2024-04-17T23:34:45.764534Z ERROR jd_client: Error: File 'no-such-file.toml' does not exist!
> ```
> 
> a few remarks:
> 
>     * although it was not explicitly stated on the original issue description, it would be nice if you could replicate this solution to the `translator` role implementation, because it suffers from the same bug.
> 
>     * the `Rustfmt` CI test is failing. Please run `cargo fmt` to make sure the code is properly formatted. It is a good practice to do this before every commit, but you could also just add one final commit doing the formatting for all the edited files.

A run of `cargo fmt` gives the following warnings:
```
Warning: can't set `imports_indent = Block`, unstable features are only available in nightly channel.
Warning: can't set `imports_layout = Mixed`, unstable features are only available in nightly channel.
Warning: can't set `imports_granularity = Crate`, unstable features are only available in nightly channel.
Warning: can't set `imports_indent = Block`, unstable features are only available in nightly channel.
Warning: can't set `imports_layout = Mixed`, unstable features are only available in nightly channel.
Warning: can't set `imports_granularity = Crate`, unstable features are only available in nightly channel.
Warning: can't set `imports_indent = Block`, unstable features are only available in nightly channel.
```
that feels odd

2024-04-18 12:04 UTC, plebhash commented
> > great job! I was able to test successfully on `roles/jd-client`:
> > ```
> > $ cargo run -- -c no-such-file.toml
> > ...
> > 2024-04-17T23:34:45.764534Z ERROR jd_client: Error: File 'no-such-file.toml' does not exist!
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > a few remarks:
> > ```
> > * although it was not explicitly stated on the original issue description, it would be nice if you could replicate this solution to the `translator` role implementation, because it suffers from the same bug.
> > 
> > * the `Rustfmt` CI test is failing. Please run `cargo fmt` to make sure the code is properly formatted. It is a good practice to do this before every commit, but you could also just add one final commit doing the formatting for all the edited files.
> > ```
> 
> A run of `cargo fmt` gives the following warnings:
> 
> ```
> Warning: can't set `imports_indent = Block`, unstable features are only available in nightly channel.
> Warning: can't set `imports_layout = Mixed`, unstable features are only available in nightly channel.
> Warning: can't set `imports_granularity = Crate`, unstable features are only available in nightly channel.
> Warning: can't set `imports_indent = Block`, unstable features are only available in nightly channel.
> Warning: can't set `imports_layout = Mixed`, unstable features are only available in nightly channel.
> Warning: can't set `imports_granularity = Crate`, unstable features are only available in nightly channel.
> Warning: can't set `imports_indent = Block`, unstable features are only available in nightly channel.
> ```
> 
> that feels odd

yeah we need to fix that, but for now you can just go ahead and run `cargo fmt` while safely ignoring those warnings

2024-04-18 12:07 UTC, rockcoolsaint commented
> > > great job! I was able to test successfully on `roles/jd-client`:
> > > ```
> > > $ cargo run -- -c no-such-file.toml
> > > ...
> > > 2024-04-17T23:34:45.764534Z ERROR jd_client: Error: File 'no-such-file.toml' does not exist!
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > a few remarks:
> > > ```
> > > * although it was not explicitly stated on the original issue description, it would be nice if you could replicate this solution to the `translator` role implementation, because it suffers from the same bug.
> > > 
> > > * the `Rustfmt` CI test is failing. Please run `cargo fmt` to make sure the code is properly formatted. It is a good practice to do this before every commit, but you could also just add one final commit doing the formatting for all the edited files.
> > > ```
> > 
> > 
> > A run of `cargo fmt` gives the following warnings:
> > ```
> > Warning: can't set `imports_indent = Block`, unstable features are only available in nightly channel.
> > Warning: can't set `imports_layout = Mixed`, unstable features are only available in nightly channel.
> > Warning: can't set `imports_granularity = Crate`, unstable features are only available in nightly channel.
> > Warning: can't set `imports_indent = Block`, unstable features are only available in nightly channel.
> > Warning: can't set `imports_layout = Mixed`, unstable features are only available in nightly channel.
> > Warning: can't set `imports_granularity = Crate`, unstable features are only available in nightly channel.
> > Warning: can't set `imports_indent = Block`, unstable features are only available in nightly channel.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > that feels odd
> 
> yeah we need to fix that, but for now you can just go ahead and run `cargo fmt` while safely ignoring those warnings

I get the warning upon running `cargo fmt`. Is there anything else I'm supposed to run?

2024-04-18 14:06 UTC, merged